/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v2/sessions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create an agent session */
        post: operations["createSession"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v2/runs/chat": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Run a chat agent task */
        post: operations["runChat"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v2/runs/chat/stream": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Stream a chat agent task */
        post: operations["runChatStream"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v2/runs/ops": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Run an operations supervisor workflow */
        post: operations["runOps"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v2/runs/{runId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a run with event summary */
        get: operations["getRun"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v2/runs/{runId}/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List stored run events */
        get: operations["listRunEvents"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v2/runs/{runId}/resume": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Resume an interrupted run */
        post: operations["resumeRun"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v2/knowledge/documents": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Upload a knowledge document */
        post: operations["uploadKnowledgeDocument"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v2/knowledge/index-jobs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create an asynchronous knowledge indexing job */
        post: operations["createKnowledgeIndexJob"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v2/tools/mcp": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List MCP tools discovered from the MCP server */
        get: operations["listMCPTools"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        CreateSessionRequest: {
            title?: string;
            /** @example general */
            mode?: string;
        };
        ChatRunRequest: {
            sessionId: string;
            query: string;
            /** @default 4 */
            topK: number;
        };
        OpsRunRequest: {
            sessionId: string;
            alertTitle: string;
            serviceName: string;
            /** @enum {string} */
            severity: "critical" | "warning" | "info";
            summary: string;
        };
        ResumeRunRequest: {
            interruptId?: string;
            approved?: boolean;
            note?: string;
        };
        CreateKnowledgeIndexJobRequest: {
            documentIds?: string[];
            /** @default 500 */
            chunkSize: number;
            /** @default 80 */
            overlap: number;
            /** @default 4 */
            topK: number;
        };
        Session: {
            id: string;
            title: string;
            mode: string;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
        };
        InterruptContext: {
            id: string;
            address: string;
            /** @description Interrupt metadata provided by the paused component */
            info?: unknown;
            isRootCause: boolean;
        };
        InterruptData: {
            contexts?: components["schemas"]["InterruptContext"][];
        };
        RunEvent: {
            id: string;
            runId: string;
            sequence: number;
            /** @example tool_call */
            eventType: string;
            agentName?: string;
            role?: string;
            toolName?: string;
            content?: string;
            /** @description Event-specific JSON payload */
            payload?: unknown;
            /** Format: date-time */
            createdAt: string;
        };
        Run: {
            id: string;
            sessionId: string;
            /** @enum {string} */
            runType: "chat" | "ops";
            /** @enum {string} */
            status: "running" | "completed" | "interrupted" | "failed";
            summary: string;
            errorMessage?: string;
            checkpointId: string;
            interrupt?: components["schemas"]["InterruptData"];
            events?: components["schemas"]["RunEvent"][];
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
            /** Format: date-time */
            completedAt?: string;
        };
        KnowledgeDocument: {
            id: string;
            fileName: string;
            title: string;
            contentType: string;
            filePath: string;
            status: string;
            sourceType: string;
            content?: string;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
        };
        KnowledgeIndexJob: {
            id: string;
            documentId?: string;
            /** @enum {string} */
            status: "queued" | "running" | "completed" | "failed";
            collectionName: string;
            chunkSize: number;
            overlap: number;
            topK: number;
            indexedChunks: number;
            errorMessage?: string;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
            /** Format: date-time */
            completedAt?: string;
        };
        MCPToolDescriptor: {
            name: string;
            description?: string;
            schemaJson?: string;
        };
        SessionResponse: {
            message: string;
            data: components["schemas"]["Session"];
        };
        RunResponse: {
            message: string;
            data: components["schemas"]["Run"];
        };
        RunEventListResponse: {
            message: string;
            data: components["schemas"]["RunEvent"][];
        };
        KnowledgeDocumentResponse: {
            message: string;
            data: components["schemas"]["KnowledgeDocument"];
        };
        KnowledgeIndexJobResponse: {
            message: string;
            data: components["schemas"]["KnowledgeIndexJob"];
        };
        MCPToolListResponse: {
            message: string;
            data: components["schemas"]["MCPToolDescriptor"][];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    createSession: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateSessionRequest"];
            };
        };
        responses: {
            /** @description Session created */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionResponse"];
                };
            };
        };
    };
    runChat: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChatRunRequest"];
            };
        };
        responses: {
            /** @description Chat run result */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunResponse"];
                };
            };
        };
    };
    runChatStream: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChatRunRequest"];
            };
        };
        responses: {
            /** @description SSE stream of run events */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/event-stream": string;
                };
            };
        };
    };
    runOps: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OpsRunRequest"];
            };
        };
        responses: {
            /** @description Ops run result */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunResponse"];
                };
            };
        };
    };
    getRun: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                runId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Run detail */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunResponse"];
                };
            };
        };
    };
    listRunEvents: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                runId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Run events */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunEventListResponse"];
                };
            };
        };
    };
    resumeRun: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                runId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ResumeRunRequest"];
            };
        };
        responses: {
            /** @description Resumed run result */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunResponse"];
                };
            };
        };
    };
    uploadKnowledgeDocument: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": {
                    /** Format: binary */
                    file: string;
                };
            };
        };
        responses: {
            /** @description Uploaded knowledge document */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["KnowledgeDocumentResponse"];
                };
            };
        };
    };
    createKnowledgeIndexJob: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateKnowledgeIndexJobRequest"];
            };
        };
        responses: {
            /** @description Knowledge index job */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["KnowledgeIndexJobResponse"];
                };
            };
        };
    };
    listMCPTools: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Tool catalog */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MCPToolListResponse"];
                };
            };
        };
    };
}
