/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/chat": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Ask a question with session memory */
        post: operations["postChat"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/chat/stream": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Stream a chat response through SSE */
        post: operations["postChatStream"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/ops/diagnose": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Diagnose an OnCall alert and return an execution trail */
        post: operations["postDiagnose"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/knowledge/files": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Upload a knowledge file */
        post: operations["postKnowledgeFile"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/knowledge/index": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Index uploaded or seeded knowledge documents */
        post: operations["postKnowledgeIndex"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/runs/{runId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Query a stored run detail */
        get: operations["getRunDetail"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        ApiResponse: {
            /** @example OK */
            message: string;
        };
        Reference: {
            documentId: string;
            title: string;
            excerpt: string;
            /** Format: float */
            score: number;
        };
        ToolCallRecord: {
            name: string;
            input: string;
            output: string;
            /** @enum {string} */
            status: "success" | "failed";
        };
        ChatRequest: {
            /** @example session-001 */
            sessionId: string;
            /** @example 支付服务 CPU 告警应该怎么排查？ */
            question: string;
            /** @default 3 */
            topK: number;
        };
        ChatResponseData: {
            sessionId: string;
            answer: string;
            references: components["schemas"]["Reference"][];
            suggestions: string[];
        };
        ChatResponse: components["schemas"]["ApiResponse"] & {
            data: components["schemas"]["ChatResponseData"];
        };
        DiagnoseRequest: {
            /** @example payment-service cpu usage high */
            alertTitle: string;
            /** @example payment-service */
            serviceName: string;
            /** @enum {string} */
            severity: "critical" | "warning" | "info";
            /** @example 支付服务 CPU 连续 5 分钟高于 90%，错误率上升。 */
            summary: string;
            /** @default ops-session-001 */
            sessionId: string;
        };
        DiagnoseResponseData: {
            runId: string;
            result: string;
            detail: string[];
            references: components["schemas"]["Reference"][];
            toolCalls: components["schemas"]["ToolCallRecord"][];
        };
        DiagnoseResponse: components["schemas"]["ApiResponse"] & {
            data: components["schemas"]["DiagnoseResponseData"];
        };
        UploadFileResponseData: {
            documentId: string;
            fileName: string;
            filePath: string;
            fileSize: number;
            /** @enum {string} */
            status: "uploaded" | "indexed";
        };
        UploadFileResponse: components["schemas"]["ApiResponse"] & {
            data: components["schemas"]["UploadFileResponseData"];
        };
        KnowledgeIndexRequest: {
            documentIds?: string[];
            /** @default 220 */
            chunkSize: number;
            /** @default 40 */
            overlap: number;
            /** @default 3 */
            topK: number;
        };
        KnowledgeIndexResponseData: {
            indexedDocuments: number;
            indexedChunks: number;
            chunkSize: number;
            overlap: number;
            topK: number;
        };
        KnowledgeIndexResponse: components["schemas"]["ApiResponse"] & {
            data: components["schemas"]["KnowledgeIndexResponseData"];
        };
        RunDetailData: {
            runId: string;
            /** @enum {string} */
            runType: "chat" | "ops";
            /** @enum {string} */
            status: "completed" | "failed";
            summary: string;
            detail: string[];
            references: components["schemas"]["Reference"][];
            toolCalls: components["schemas"]["ToolCallRecord"][];
            /** Format: date-time */
            createdAt: string;
        };
        RunDetailResponse: components["schemas"]["ApiResponse"] & {
            data: components["schemas"]["RunDetailData"];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    postChat: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChatRequest"];
            };
        };
        responses: {
            /** @description Chat response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChatResponse"];
                };
            };
        };
    };
    postChatStream: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChatRequest"];
            };
        };
        responses: {
            /** @description SSE stream */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/event-stream": string;
                };
            };
        };
    };
    postDiagnose: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DiagnoseRequest"];
            };
        };
        responses: {
            /** @description Diagnosis report */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DiagnoseResponse"];
                };
            };
        };
    };
    postKnowledgeFile: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": {
                    /** Format: binary */
                    file: string;
                };
            };
        };
        responses: {
            /** @description Upload result */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UploadFileResponse"];
                };
            };
        };
    };
    postKnowledgeIndex: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["KnowledgeIndexRequest"];
            };
        };
        responses: {
            /** @description Indexing result */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["KnowledgeIndexResponse"];
                };
            };
        };
    };
    getRunDetail: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                runId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Stored run detail */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunDetailResponse"];
                };
            };
        };
    };
}
