root = "."
testdata_dir = "testdata"
tmp_dir = "tmp"

[build]
cmd = "go build -buildvcs=false -o ./tmp/aegisflow-api ."
bin = "./tmp/aegisflow-api"
full_bin = "./tmp/aegisflow-api"
include_ext = ["go", "yaml"]
exclude_dir = ["tmp", "resource/uploads"]
delay = 300
stop_on_error = true
send_interrupt = true

[log]
time = true

[screen]
clear_on_rebuild = true

